SELECT "Id",
       "FarmerId",
       "VegetableName",
       "Variety",
       "Grade",
       "PricePerKg",
       "AvailableQuantityKg",
       "Unit",
       "Description",
       "ImageUrl",
       "IsOrganic",
       "IsExportReady",
       "CertificationUrl",
       "Status",
       "HarvestDate",
       "ExpiryDate",
       "CreatedAt",
       "UpdatedAt",
       "District"
FROM public."Products"
LIMIT 1000;